linters:
  enable:
    - revive
    - stylecheck

linters-settings:
  revive:
    rules:
      - name: exported      
        severity: warning

issues:
  exclude-use-default: false  

run:
  tests: true
